# Generated by Django 5.2.3 on 2025-06-22 13:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MunicipalityWideForeignEmploymentCountries",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("country", models.CharField(max_length=100, verbose_name="देश")),
                (
                    "population",
                    models.PositiveIntegerField(default=0, verbose_name="जनसंख्या"),
                ),
            ],
            options={
                "verbose_name": "वैदेशिक रोजगार देश",
                "verbose_name_plural": "वैदेशिक रोजगार देश",
                "unique_together": {("country",)},
            },
        ),
    ]
