# Generated by Django 5.2.3 on 2025-06-15 10:14

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BridgeInfrastructure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="पुलको नाम")),
                (
                    "name_nepali",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="पुलको नाम (नेपाली)"
                    ),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "length_meters",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="लम्बाइ (मिटर)"
                    ),
                ),
                (
                    "width_meters",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="चौडाइ (मिटर)"
                    ),
                ),
                (
                    "is_suspension_bridge",
                    models.BooleanField(default=False, verbose_name="झोलुंगे पुल हो"),
                ),
                (
                    "construction_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="निर्माण वर्ष"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "उत्कृष्ट"),
                            ("GOOD", "राम्रो"),
                            ("FAIR", "मध्यम"),
                            ("POOR", "खराब"),
                            ("VERY_POOR", "अत्यन्त खराब"),
                        ],
                        max_length=20,
                        verbose_name="पुलको अवस्था",
                    ),
                ),
                (
                    "connects_areas",
                    models.TextField(blank=True, verbose_name="जोड्ने क्षेत्रहरू"),
                ),
            ],
            options={
                "verbose_name": "पुल पूर्वाधार",
                "verbose_name_plural": "पुल पूर्वाधार",
            },
        ),
        migrations.CreateModel(
            name="CommunicationInfrastructure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="सुविधाको नाम")),
                (
                    "name_nepali",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="सुविधाको नाम (नेपाली)"
                    ),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("MOBILE_TOWER", "मोबाइल टावर"),
                            ("INTERNET_SERVICE", "इन्टरनेट सेवा"),
                            ("RADIO_STATION", "रेडियो स्टेसन"),
                            ("POST_OFFICE", "हुलाक कार्यालय"),
                            ("TELECOM_OFFICE", "दूरसंचार कार्यालय"),
                        ],
                        max_length=30,
                        verbose_name="सुविधाको प्रकार",
                    ),
                ),
                (
                    "service_provider",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="सेवा प्रदायक"
                    ),
                ),
                (
                    "is_operational",
                    models.BooleanField(default=True, verbose_name="सञ्चालनमा छ"),
                ),
                (
                    "installation_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="स्थापना वर्ष"
                    ),
                ),
            ],
            options={
                "verbose_name": "सञ्चार पूर्वाधार",
                "verbose_name_plural": "सञ्चार पूर्वाधार",
            },
        ),
        migrations.CreateModel(
            name="GovernmentBuilding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="भवनको नाम")),
                (
                    "name_nepali",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="भवनको नाम (नेपाली)"
                    ),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "building_type",
                    models.CharField(
                        choices=[
                            ("MUNICIPALITY_OFFICE", "नगरपालिका कार्यालय"),
                            ("WARD_OFFICE", "वडा कार्यालय"),
                            ("SCHOOL", "विद्यालय"),
                            ("HEALTH_POST", "स्वास्थ्य चौकी"),
                            ("POLICE_POST", "प्रहरी चौकी"),
                            ("COMMUNITY_HALL", "सामुदायिक भवन"),
                            ("LIBRARY", "पुस्तकालय"),
                            ("COOPERATIVE", "सहकारी"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=30,
                        verbose_name="भवनको प्रकार",
                    ),
                ),
                (
                    "construction_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="निर्माण वर्ष"
                    ),
                ),
                (
                    "is_earthquake_resistant",
                    models.BooleanField(default=False, verbose_name="भूकम्प प्रतिरोधी छ"),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "उत्कृष्ट"),
                            ("GOOD", "राम्रो"),
                            ("FAIR", "मध्यम"),
                            ("POOR", "खराब"),
                            ("NEEDS_REPAIR", "मर्मत आवश्यक"),
                        ],
                        default="GOOD",
                        max_length=20,
                        verbose_name="भवनको अवस्था",
                    ),
                ),
                (
                    "total_rooms",
                    models.PositiveIntegerField(default=1, verbose_name="कुल कोठा संख्या"),
                ),
            ],
            options={
                "verbose_name": "सरकारी भवन",
                "verbose_name_plural": "सरकारी भवनहरू",
            },
        ),
        migrations.CreateModel(
            name="PowerGeneration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="पावर स्थानको नाम"),
                ),
                (
                    "name_nepali",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="पावर स्थानको नाम (नेपाली)",
                    ),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "generation_type",
                    models.CharField(
                        choices=[
                            ("HYDRO", "जलविद्युत्"),
                            ("SOLAR", "सौर्य उर्जा"),
                            ("WIND", "वायु उर्जा"),
                            ("BIOGAS", "बायोग्यास"),
                        ],
                        max_length=20,
                        verbose_name="उत्पादनको प्रकार",
                    ),
                ),
                (
                    "capacity_kw",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="क्षमता (किलोवाट)"
                    ),
                ),
                (
                    "households_served",
                    models.PositiveIntegerField(
                        default=0, verbose_name="सेवा पाउने घरपरिवार"
                    ),
                ),
                (
                    "is_operational",
                    models.BooleanField(default=True, verbose_name="सञ्चालनमा छ"),
                ),
                (
                    "installation_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="स्थापना वर्ष"
                    ),
                ),
            ],
            options={
                "verbose_name": "विद्युत् उत्पादन",
                "verbose_name_plural": "विद्युत् उत्पादन",
            },
        ),
        migrations.CreateModel(
            name="PublicFacility",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="सुविधाको नाम")),
                (
                    "name_nepali",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="सुविधाको नाम (नेपाली)"
                    ),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("SLAUGHTERHOUSE", "पशुवधशाला"),
                            ("CREMATION_GROUND", "शव दाहस्थल"),
                            ("CEMETERY", "चिहान"),
                            ("PUBLIC_TOILET", "सार्वजनिक शौचालय"),
                            ("WATER_TANK", "पानी ट्याङ्की"),
                            ("MARKET", "बजार"),
                            ("BUS_PARK", "बस पार्क"),
                            ("DRINKING_WATER_SOURCE", "खानेपानी स्रोत"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=30,
                        verbose_name="सुविधाको प्रकार",
                    ),
                ),
                (
                    "is_operational",
                    models.BooleanField(default=True, verbose_name="सञ्चालनमा छ"),
                ),
                (
                    "construction_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="निर्माण वर्ष"
                    ),
                ),
                (
                    "capacity_or_size",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="क्षमता वा आकार"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "उत्कृष्ट"),
                            ("GOOD", "राम्रो"),
                            ("FAIR", "मध्यम"),
                            ("POOR", "खराब"),
                        ],
                        default="GOOD",
                        max_length=20,
                        verbose_name="सुविधाको अवस्था",
                    ),
                ),
            ],
            options={
                "verbose_name": "सार्वजनिक सुविधा",
                "verbose_name_plural": "सार्वजनिक सुविधाहरू",
            },
        ),
        migrations.CreateModel(
            name="RoadInfrastructure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="सडकको नाम")),
                (
                    "name_nepali",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="सडकको नाम (नेपाली)"
                    ),
                ),
                (
                    "road_type",
                    models.CharField(
                        choices=[
                            ("HIGHWAY", "राजमार्ग"),
                            ("FEEDER", "फिडर सडक"),
                            ("RURAL", "ग्रामीण सडक"),
                            ("URBAN", "शहरी सडक"),
                            ("TRAIL", "ट्रेल"),
                            ("FOOTPATH", "पैदल बाटो"),
                        ],
                        max_length=20,
                        verbose_name="सडकको प्रकार",
                    ),
                ),
                (
                    "surface_type",
                    models.CharField(
                        choices=[
                            ("BLACKTOPPED", "कालोपत्रे"),
                            ("GRAVELED", "ढुंगामाटो"),
                            ("EARTHEN", "कच्ची"),
                            ("CONCRETE", "कंक्रिट"),
                        ],
                        max_length=20,
                        verbose_name="सडकको सतह",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "उत्कृष्ट"),
                            ("GOOD", "राम्रो"),
                            ("FAIR", "मध्यम"),
                            ("POOR", "खराब"),
                            ("VERY_POOR", "अत्यन्त खराब"),
                        ],
                        max_length=20,
                        verbose_name="सडकको अवस्था",
                    ),
                ),
                (
                    "length_km",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="लम्बाइ (किलोमिटर)"
                    ),
                ),
                (
                    "width_meters",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="चौडाइ (मिटर)",
                    ),
                ),
                (
                    "construction_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="निर्माण वर्ष"
                    ),
                ),
                (
                    "last_maintenance_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="अन्तिम मर्मत मिति"
                    ),
                ),
                (
                    "connects_wards",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="जोड्ने वडाहरू"
                    ),
                ),
            ],
            options={
                "verbose_name": "सडक पूर्वाधार",
                "verbose_name_plural": "सडक पूर्वाधार",
            },
        ),
        migrations.CreateModel(
            name="VehicleRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("BUS", "बस"),
                            ("MICROBUS", "माइक्रोबस"),
                            ("JEEP", "जीप"),
                            ("TRUCK", "ट्रक"),
                            ("TRACTOR", "ट्राक्टर"),
                            ("MOTORBIKE", "मोटरसाइकल"),
                            ("BICYCLE", "साइकल"),
                        ],
                        max_length=20,
                        verbose_name="सवारी साधनको प्रकार",
                    ),
                ),
                (
                    "registered_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="दर्ता भएका सवारी साधन"
                    ),
                ),
            ],
            options={
                "verbose_name": "सवारी साधन दर्ता",
                "verbose_name_plural": "सवारी साधन दर्ता",
                "unique_together": {("ward_number", "vehicle_type")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseCommunicationAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("MOBILE_PHONE", "मोबाइल फोन"),
                            ("LANDLINE", "ल्यान्डलाइन"),
                            ("INTERNET", "इन्टरनेट"),
                            ("RADIO", "रेडियो"),
                            ("TELEVISION", "टेलिभिजन"),
                            ("NEWSPAPER", "पत्रपत्रिका"),
                            ("POST_OFFICE", "हुलाक कार्यालय"),
                        ],
                        max_length=20,
                        verbose_name="सञ्चार सेवाको प्रकार",
                    ),
                ),
                (
                    "households_with_access",
                    models.PositiveIntegerField(
                        default=0, verbose_name="पहुँच भएका घरपरिवार"
                    ),
                ),
                (
                    "coverage_quality",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "उत्कृष्ट"),
                            ("GOOD", "राम्रो"),
                            ("FAIR", "मध्यम"),
                            ("POOR", "खराब"),
                        ],
                        default="GOOD",
                        max_length=20,
                        verbose_name="सेवाको गुणस्तर",
                    ),
                ),
            ],
            options={
                "verbose_name": "वडागत सञ्चार पहुँच",
                "verbose_name_plural": "वडागत सञ्चार पहुँच",
                "unique_together": {("ward_number", "service_type")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseCookingFuel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("FIREWOOD", "दाउरा"),
                            ("LPG", "एलपीजी"),
                            ("BIOGAS", "बायोग्यास"),
                            ("KEROSENE", "मट्टितेल"),
                            ("ELECTRICITY", "विद्युत्"),
                            ("IMPROVED_STOVE", "सुधारिएको चुल्हो"),
                            ("DUNG", "गोबर"),
                        ],
                        max_length=20,
                        verbose_name="खाना पकाउने इन्धन",
                    ),
                ),
                (
                    "households_using",
                    models.PositiveIntegerField(
                        default=0, verbose_name="प्रयोग गर्ने घरपरिवार"
                    ),
                ),
            ],
            options={
                "verbose_name": "वडागत खाना पकाउने इन्धन",
                "verbose_name_plural": "वडागत खाना पकाउने इन्धन",
                "unique_together": {("ward_number", "fuel_type")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseEnergyAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "energy_source",
                    models.CharField(
                        choices=[
                            ("GRID_ELECTRICITY", "राष्ट्रिय विद्युत् प्रणाली"),
                            ("SOLAR", "सौर्य उर्जा"),
                            ("MICRO_HYDRO", "सानो जलविद्युत्"),
                            ("BIOGAS", "बायोग्यास"),
                            ("WIND", "वायु उर्जा"),
                            ("GENERATOR", "जेनेरेटर"),
                            ("KEROSENE", "मट्टितेल"),
                            ("CANDLE", "मैनबत्ती"),
                            ("BATTERY", "ब्याट्री"),
                        ],
                        max_length=30,
                        verbose_name="उर्जाको स्रोत",
                    ),
                ),
                (
                    "households_with_access",
                    models.PositiveIntegerField(
                        default=0, verbose_name="पहुँच भएका घरपरिवार"
                    ),
                ),
            ],
            options={
                "verbose_name": "वडागत उर्जा पहुँच",
                "verbose_name_plural": "वडागत उर्जा पहुँच",
                "unique_together": {("ward_number", "energy_source")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseHousingMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "roof_material",
                    models.CharField(
                        choices=[
                            ("TILE", "टाइल"),
                            ("TIN", "जस्ता पाता"),
                            ("CONCRETE", "कंक्रिट"),
                            ("SLATE", "स्लेट"),
                            ("THATCH", "खर"),
                            ("WOOD", "काठ"),
                        ],
                        max_length=20,
                        verbose_name="छानाको सामग्री",
                    ),
                ),
                (
                    "wall_material",
                    models.CharField(
                        choices=[
                            ("CONCRETE", "कंक्रिट"),
                            ("BRICK", "इट्टा"),
                            ("STONE", "ढुंगा"),
                            ("WOOD", "काठ"),
                            ("BAMBOO", "बाँस"),
                            ("MUD", "माटो"),
                        ],
                        max_length=20,
                        verbose_name="भित्ताको सामग्री",
                    ),
                ),
                (
                    "households_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="घरपरिवार संख्या"
                    ),
                ),
            ],
            options={
                "verbose_name": "वडागत आवास सामग्री",
                "verbose_name_plural": "वडागत आवास सामग्री",
                "unique_together": {("ward_number", "roof_material", "wall_material")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseTransportAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "time_to_municipality_center_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="नगरपालिका केन्द्र पुग्न लाग्ने समय (मिनेट)",
                    ),
                ),
                (
                    "time_to_district_center_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="जिल्ला केन्द्र पुग्न लाग्ने समय (घण्टा)",
                    ),
                ),
                (
                    "has_all_weather_road",
                    models.BooleanField(default=False, verbose_name="वर्षभरि चल्ने सडक छ"),
                ),
                (
                    "public_transport_available",
                    models.BooleanField(
                        default=False, verbose_name="सार्वजनिक यातायात उपलब्ध छ"
                    ),
                ),
            ],
            options={
                "verbose_name": "वडागत यातायात पहुँच",
                "verbose_name_plural": "वडागत यातायात पहुँच",
                "unique_together": {("ward_number",)},
            },
        ),
    ]
