# Generated by Django 5.2.3 on 2025-06-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wardwisetimetoactiveroad",
            name="time_duration",
            field=models.CharField(
                choices=[
                    ("UNDER_15_MIN", "१५ मिनेट भन्दा कम"),
                    ("UNDER_30_MIN", "१५-३० मिनेट"),
                    ("UNDER_1_HOUR", "३०-६० मिनेट"),
                    ("1_HOUR_OR_MORE", "१ घण्टा वा बढी"),
                ],
                max_length=25,
                verbose_name="सक्रिय सडकमा पुग्न लाग्ने समय",
            ),
        ),
        migrations.AlterField(
            model_name="wardwisetimetomarketcenter",
            name="time_duration",
            field=models.CharField(
                choices=[
                    ("UNDER_15_MIN", "१५ मिनेट भन्दा कम"),
                    ("UNDER_30_MIN", "१५-३० मिनेट"),
                    ("UNDER_1_HOUR", "३०-६० मिनेट"),
                    ("1_HOUR_OR_MORE", "१ घण्टा वा बढी"),
                ],
                max_length=25,
                verbose_name="बजार केन्द्रमा पुग्न लाग्ने समय",
            ),
        ),
        migrations.AlterField(
            model_name="wardwisetimetopublictransport",
            name="time_duration",
            field=models.CharField(
                choices=[
                    ("UNDER_15_MIN", "१५ मिनेट भन्दा कम"),
                    ("UNDER_30_MIN", "१५-३० मिनेट"),
                    ("UNDER_1_HOUR", "३०-६० मिनेट"),
                    ("1_HOUR_OR_MORE", "१ घण्टा वा बढी"),
                ],
                max_length=25,
                verbose_name="सार्वजनिक यातायातमा पुग्न लाग्ने समय",
            ),
        ),
    ]
