# Generated by Django 5.2.3 on 2025-06-16 11:40

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemographicSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default='singleton', max_length=36, primary_key=True, serialize=False)),
                ('total_population', models.PositiveIntegerField(blank=True, null=True, verbose_name='कुल जनसंख्या')),
                ('population_male', models.PositiveIntegerField(blank=True, null=True, verbose_name='पुरुष जनसंख्या')),
                ('population_female', models.PositiveIntegerField(blank=True, null=True, verbose_name='महिला जनसंख्या')),
                ('population_other', models.PositiveIntegerField(blank=True, null=True, verbose_name='अन्य जनसंख्या')),
                ('population_absentee_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='कुल अनुपस्थित जनसंख्या')),
                ('population_male_absentee', models.PositiveIntegerField(blank=True, null=True, verbose_name='अनुपस्थित पुरुष जनसंख्या')),
                ('population_female_absentee', models.PositiveIntegerField(blank=True, null=True, verbose_name='अनुपस्थित महिला जनसंख्या')),
                ('population_other_absentee', models.PositiveIntegerField(blank=True, null=True, verbose_name='अनुपस्थित अन्य जनसंख्या')),
                ('sex_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='लिङ्ग अनुपात')),
                ('total_households', models.PositiveIntegerField(blank=True, null=True, verbose_name='कुल घरपरिवार')),
                ('average_household_size', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='औसत घरपरिवार आकार')),
                ('population_density', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='जनसंख्या घनत्व')),
                ('population_0_to_14', models.PositiveIntegerField(blank=True, null=True, verbose_name='०-१४ वर्ष जनसंख्या')),
                ('population_15_to_59', models.PositiveIntegerField(blank=True, null=True, verbose_name='१५-५९ वर्ष जनसंख्या')),
                ('population_60_and_above', models.PositiveIntegerField(blank=True, null=True, verbose_name='६० वर्षभन्दा माथि जनसंख्या')),
                ('growth_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='वृद्धि दर')),
                ('literacy_rate_above_15', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='१५ वर्षभन्दा माथि साक्षरता दर')),
                ('literacy_rate_15_to_24', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='१५-२४ वर्ष साक्षरता दर')),
            ],
            options={
                'verbose_name': 'जनसांख्यिकीय सारांश',
                'verbose_name_plural': 'जनसांख्यिकीय सारांश',
            },
        ),
        migrations.CreateModel(
            name='WardAgeGenderWiseDeceasedPopulation',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='वडा नं.')),
                ('age_group', models.CharField(choices=[('AGE_0_4', '०-४ वर्ष'), ('AGE_5_9', '५-९ वर्ष'), ('AGE_10_14', '१०-१४ वर्ष'), ('AGE_15_19', '१५-१९ वर्ष'), ('AGE_20_24', '२०-२४ वर्ष'), ('AGE_25_29', '२५-२९ वर्ष'), ('AGE_30_34', '३०-३४ वर्ष'), ('AGE_35_39', '३५-३९ वर्ष'), ('AGE_40_44', '४०-४४ वर्ष'), ('AGE_45_49', '४५-४९ वर्ष'), ('AGE_50_54', '५०-५४ वर्ष'), ('AGE_55_59', '५५-५९ वर्ष'), ('AGE_60_64', '६०-६४ वर्ष'), ('AGE_65_69', '६५-६९ वर्ष'), ('AGE_70_74', '७०-७४ वर्ष'), ('AGE_75_AND_ABOVE', '७५ वर्षभन्दा माथि')], max_length=20, verbose_name='उमेर समूह')),
                ('gender', models.CharField(choices=[('MALE', 'पुरुष'), ('FEMALE', 'महिला'), ('OTHER', 'अन्य')], max_length=10, verbose_name='लिङ्ग')),
                ('deceased_population', models.PositiveIntegerField(default=0, verbose_name='मृत्यु जनसंख्या')),
            ],
            options={
                'verbose_name': 'वडागत उमेर लिङ्गअनुसार मृत्यु जनसंख्या',
                'verbose_name_plural': 'वडागत उमेर लिङ्गअनुसार मृत्यु जनसंख्या',
                'unique_together': {('ward_number', 'age_group', 'gender')},
            },
        ),
        migrations.CreateModel(
            name='WardAgeWiseEconomicallyActivePopulation',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='वडा नं.')),
                ('age_group', models.CharField(choices=[('AGE_0_4', '०-४ वर्ष'), ('AGE_5_9', '५-९ वर्ष'), ('AGE_10_14', '१०-१४ वर्ष'), ('AGE_15_19', '१५-१९ वर्ष'), ('AGE_20_24', '२०-२४ वर्ष'), ('AGE_25_29', '२५-२९ वर्ष'), ('AGE_30_34', '३०-३४ वर्ष'), ('AGE_35_39', '३५-३९ वर्ष'), ('AGE_40_44', '४०-४४ वर्ष'), ('AGE_45_49', '४५-४९ वर्ष'), ('AGE_50_54', '५०-५४ वर्ष'), ('AGE_55_59', '५५-५९ वर्ष'), ('AGE_60_64', '६०-६४ वर्ष'), ('AGE_65_69', '६५-६९ वर्ष'), ('AGE_70_74', '७०-७४ वर्ष'), ('AGE_75_AND_ABOVE', '७५ वर्षभन्दा माथि')], max_length=20, verbose_name='उमेर समूह')),
                ('population', models.PositiveIntegerField(default=0, verbose_name='आर्थिक रूपमा सक्रिय जनसंख्या')),
            ],
            options={
                'verbose_name': 'वडागत उमेरअनुसार आर्थिक रूपमा सक्रिय जनसंख्या',
                'verbose_name_plural': 'वडागत उमेरअनुसार आर्थिक रूपमा सक्रिय जनसंख्या',
                'unique_together': {('ward_number', 'age_group')},
            },
        ),
        migrations.CreateModel(
            name='WardAgeWisePopulation',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='वडा नं.')),
                ('age_group', models.CharField(choices=[('AGE_0_4', '०-४ वर्ष'), ('AGE_5_9', '५-९ वर्ष'), ('AGE_10_14', '१०-१४ वर्ष'), ('AGE_15_19', '१५-१९ वर्ष'), ('AGE_20_24', '२०-२४ वर्ष'), ('AGE_25_29', '२५-२९ वर्ष'), ('AGE_30_34', '३०-३४ वर्ष'), ('AGE_35_39', '३५-३९ वर्ष'), ('AGE_40_44', '४०-४४ वर्ष'), ('AGE_45_49', '४५-४९ वर्ष'), ('AGE_50_54', '५०-५४ वर्ष'), ('AGE_55_59', '५५-५९ वर्ष'), ('AGE_60_64', '६०-६४ वर्ष'), ('AGE_65_69', '६५-६९ वर्ष'), ('AGE_70_74', '७०-७४ वर्ष'), ('AGE_75_AND_ABOVE', '७५ वर्षभन्दा माथि')], max_length=20, verbose_name='उमेर समूह')),
                ('gender', models.CharField(choices=[('MALE', 'पुरुष'), ('FEMALE', 'महिला'), ('OTHER', 'अन्य')], max_length=10, verbose_name='लिङ्ग')),
                ('population', models.PositiveIntegerField(default=0, verbose_name='जनसंख्या')),
            ],
            options={
                'verbose_name': 'वडागत उमेरगत जनसंख्या',
                'verbose_name_plural': 'वडागत उमेरगत जनसंख्या',
                'unique_together': {('ward_number', 'age_group', 'gender')},
            },
        ),
        migrations.CreateModel(
            name='WardSettlement',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='वडा नं.')),
                ('settlement_areas', models.JSONField(blank=True, default=list, verbose_name='मुख्य बस्तीहरु')),
            ],
            options={
                'verbose_name': 'वडागत बस्ती विवरण',
                'verbose_name_plural': 'वडागत बस्ती विवरण',
                'unique_together': {('ward_number',)},
            },
        ),
        migrations.CreateModel(
            name='WardTimeSeriesPopulation',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='वडा नं.')),
                ('ward_name', models.TextField(blank=True, null=True, verbose_name='वडाको नाम')),
                ('year', models.PositiveIntegerField(verbose_name='वर्ष')),
                ('total_population', models.PositiveIntegerField(blank=True, null=True, verbose_name='कुल जनसंख्या')),
                ('male_population', models.PositiveIntegerField(blank=True, null=True, verbose_name='पुरुष जनसंख्या')),
                ('female_population', models.PositiveIntegerField(blank=True, null=True, verbose_name='महिला जनसंख्या')),
                ('other_population', models.PositiveIntegerField(blank=True, null=True, verbose_name='अन्य जनसंख्या')),
                ('total_households', models.PositiveIntegerField(blank=True, null=True, verbose_name='कुल घरपरिवार')),
                ('average_household_size', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='औसत घरपरिवार आकार')),
                ('population_0_to_14', models.PositiveIntegerField(blank=True, null=True, verbose_name='०-१४ वर्ष जनसंख्या')),
                ('population_15_to_59', models.PositiveIntegerField(blank=True, null=True, verbose_name='१५-५९ वर्ष जनसंख्या')),
                ('population_60_and_above', models.PositiveIntegerField(blank=True, null=True, verbose_name='६० वर्षभन्दा माथि जनसंख्या')),
                ('literacy_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='साक्षरता दर')),
                ('male_literacy_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='पुरुष साक्षरता दर')),
                ('female_literacy_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='महिला साक्षरता दर')),
                ('growth_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='वृद्धि दर')),
                ('area_sq_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='क्षेत्रफल (वर्ग कि.मी.)')),
                ('population_density', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='जनसंख्या घनत्व')),
                ('sex_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='लिङ्ग अनुपात')),
            ],
            options={
                'verbose_name': 'वडागत समयश्रृंखला जनसंख्या',
                'verbose_name_plural': 'वडागत समयश्रृंखला जनसंख्या',
                'unique_together': {('ward_number', 'year')},
            },
        ),
        migrations.CreateModel(
            name='WardWiseBirthCertificatePopulation',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='वडा नं.')),
                ('with_birth_certificate', models.PositiveIntegerField(default=0, verbose_name='जन्म दर्ता भएका')),
                ('without_birth_certificate', models.PositiveIntegerField(default=0, verbose_name='जन्म दर्ता नभएका')),
                ('total_population_under_5', models.PositiveIntegerField(blank=True, null=True, verbose_name='५ वर्षमुनिका कुल बालबालिका')),
            ],
            options={
                'verbose_name': 'वडागत जन्म दर्ता जनसंख्या',
                'verbose_name_plural': 'वडागत जन्म दर्ता जनसंख्या',
                'unique_together': {('ward_number',)},
            },
        ),
        migrations.CreateModel(
            name='WardWiseBirthplaceHouseholds',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='वडा नं.')),
                ('birth_place', models.CharField(choices=[('SAME_MUNICIPALITY', 'यहि गापा/नपा'), ('SAME_DISTRICT_ANOTHER_MUNICIPALITY', 'यहि जिल्लाको अर्को गा.पा./न.पा'), ('ANOTHER_DISTRICT', 'अर्को जिल्ला'), ('ABROAD', 'विदेश')], max_length=50, verbose_name='जन्मस्थान')),
                ('households', models.PositiveIntegerField(default=0, verbose_name='घरपरिवार संख्या')),
            ],
            options={
                'verbose_name': 'वडागत जन्मस्थानअनुसार घरपरिवार',
                'verbose_name_plural': 'वडागत जन्मस्थानअनुसार घरपरिवार',
                'unique_together': {('ward_number', 'birth_place')},
            },
        ),
        migrations.CreateModel(
            name='WardWiseCastePopulation',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='वडा नं.')),
                ('caste_type', models.CharField(choices=[('BRAHMIN', 'ब्राह्मण'), ('CHHETRI', 'क्षेत्री'), ('MAGAR', 'मगर'), ('TAMANG', 'तामाङ'), ('NEWAR', 'नेवार'), ('THARU', 'थारु'), ('GURUNG', 'गुरुङ'), ('RAI', 'राई'), ('LIMBU', 'लिम्बु'), ('SHERPA', 'शेर्पा'), ('DALIT', 'दलित'), ('MADHESI', 'मधेसी'), ('MUSLIM', 'मुस्लिम'), ('OTHER', 'अन्य')], max_length=100, verbose_name='जातजाति')),
                ('population', models.PositiveIntegerField(blank=True, null=True, verbose_name='जनसंख्या')),
            ],
            options={
                'verbose_name': 'वडागत जातीय जनसंख्या',
                'verbose_name_plural': 'वडागत जातीय जनसंख्या',
                'unique_together': {('ward_number', 'caste_type')},
            },
        ),
        migrations.CreateModel(
            name='WardWiseDeathCause',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='वडा नं.')),
                ('death_cause', models.TextField(verbose_name='मृत्युको कारण')),
                ('population', models.PositiveIntegerField(default=0, verbose_name='जनसंख्या')),
            ],
            options={
                'verbose_name': 'वडागत मृत्युको कारण',
                'verbose_name_plural': 'वडागत मृत्युको कारण',
                'unique_together': {('ward_number', 'death_cause')},
            },
        ),
        migrations.CreateModel(
            name='WardWiseDisabilityCause',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='वडा नं.')),
                ('disability_cause', models.CharField(choices=[('CONGENITAL', 'जन्मजात'), ('ACCIDENT', 'दुर्घटना'), ('MALNUTRITION', 'कुपोषण'), ('DISEASE', 'रोगको कारण'), ('CONFLICT', 'द्वन्द्वको कारण'), ('OTHER', 'अन्य')], max_length=20, verbose_name='अपाङ्गताको कारण')),
                ('population', models.PositiveIntegerField(default=0, verbose_name='जनसंख्या')),
            ],
            options={
                'verbose_name': 'वडागत अपाङ्गताको कारण',
                'verbose_name_plural': 'वडागत अपाङ्गताको कारण',
                'unique_together': {('ward_number', 'disability_cause')},
            },
        ),
        migrations.CreateModel(
            name='WardWiseHouseheadGender',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='वडा नं.')),
                ('ward_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='वडाको नाम')),
                ('gender', models.CharField(choices=[('MALE', 'पुरुष'), ('FEMALE', 'महिला'), ('OTHER', 'अन्य')], max_length=10, verbose_name='घरमुखियाको लिङ्ग')),
                ('population', models.PositiveIntegerField(default=0, verbose_name='घरपरिवार संख्या')),
            ],
            options={
                'verbose_name': 'वडागत घरमुखियाको लिङ्ग',
                'verbose_name_plural': 'वडागत घरमुखियाको लिङ्ग',
                'unique_together': {('ward_number', 'gender')},
            },
        ),
        migrations.CreateModel(
            name='WardWiseMajorOccupation',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='वडा नं.')),
                ('occupation', models.TextField(verbose_name='पेशा')),
                ('population', models.PositiveIntegerField(default=0, verbose_name='जनसंख्या')),
            ],
            options={
                'verbose_name': 'वडागत मुख्य पेशा',
                'verbose_name_plural': 'वडागत मुख्य पेशा',
                'unique_together': {('ward_number', 'occupation')},
            },
        ),
        migrations.CreateModel(
            name='WardWiseMigratedHouseholds',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='वडा नं.')),
                ('migrated_from', models.CharField(choices=[('ANOTHER_DISTRICT', 'नेपालको अर्को जिल्ला'), ('SAME_DISTRICT_ANOTHER_MUNICIPALITY', 'यही जिल्लाको अर्को स्थानीय तह'), ('ABROAD', 'विदेश')], max_length=50, verbose_name='बसाइसराइको स्थान')),
                ('households', models.PositiveIntegerField(default=0, verbose_name='घरपरिवार संख्या')),
            ],
            options={
                'verbose_name': 'वडागत बसाइसराइ गरेका घरपरिवार',
                'verbose_name_plural': 'वडागत बसाइसराइ गरेका घरपरिवार',
                'unique_together': {('ward_number', 'migrated_from')},
            },
        ),
        migrations.CreateModel(
            name='WardWiseMotherTonguePopulation',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='वडा नं.')),
                ('language_type', models.CharField(choices=[('NEPALI', 'नेपाली'), ('LIMBU', 'लिम्बु'), ('RAI', 'राई'), ('HINDI', 'हिन्दी'), ('NEWARI', 'नेवारी'), ('SHERPA', 'शेर्पा'), ('TAMANG', 'तामाङ'), ('MAITHILI', 'मैथिली'), ('BHOJPURI', 'भोजपुरी'), ('THARU', 'थारु'), ('BAJJIKA', 'बज्जिका'), ('MAGAR', 'मगर'), ('DOTELI', 'डोटेली'), ('URDU', 'उर्दू'), ('AWADI', 'अवधी'), ('GURUNG', 'गुरुङ'), ('ENGLISH', 'अंग्रेजी'), ('OTHER', 'अन्य')], max_length=50, verbose_name='मातृभाषा')),
                ('population', models.PositiveIntegerField(default=0, verbose_name='जनसंख्या')),
            ],
            options={
                'verbose_name': 'वडागत मातृभाषा जनसंख्या',
                'verbose_name_plural': 'वडागत मातृभाषा जनसंख्या',
                'unique_together': {('ward_number', 'language_type')},
            },
        ),
        migrations.CreateModel(
            name='WardWiseReligionPopulation',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='वडा नं.')),
                ('religion_type', models.CharField(choices=[('HINDU', 'हिन्दू'), ('BUDDHIST', 'बौद्ध'), ('KIRANT', 'किरात'), ('CHRISTIAN', 'क्रिश्चियन'), ('ISLAM', 'इस्लाम'), ('NATURE', 'प्रकृति'), ('BON', 'बोन'), ('JAIN', 'जैन'), ('BAHAI', 'बहाई'), ('SIKH', 'सिख'), ('OTHER', 'अन्य')], max_length=20, verbose_name='धर्म')),
                ('population', models.PositiveIntegerField(default=0, verbose_name='जनसंख्या')),
            ],
            options={
                'verbose_name': 'वडागत धार्मिक जनसंख्या',
                'verbose_name_plural': 'वडागत धार्मिक जनसंख्या',
                'unique_together': {('ward_number', 'religion_type')},
            },
        ),
    ]
