# Generated by Django 5.2.3 on 2025-06-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wardagewiseeconomicallyactivepopulation',
            options={'verbose_name': 'वडागत उमेर र लिङ्गअनुसार आर्थिक रूपमा सक्रिय जनसंख्या', 'verbose_name_plural': 'वडागत उमेर र लिङ्गअनुसार आर्थिक रूपमा सक्रिय जनसंख्या'},
        ),
        migrations.AlterUniqueTogether(
            name='wardagewiseeconomicallyactivepopulation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wardagewiseeconomicallyactivepopulation',
            name='gender',
            field=models.CharField(choices=[('MALE', 'पुरुष'), ('FEMALE', 'महिला'), ('OTHER', 'अन्य')], default='MALE', max_length=20, verbose_name='लिङ्ग'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wardagewiseeconomicallyactivepopulation',
            name='age_group',
            field=models.CharField(choices=[('AGE_0_TO_14', '०-१४ वर्ष'), ('AGE_15_TO_59', '१५-५९ वर्ष'), ('AGE_60_PLUS', '६० वर्ष माथि')], max_length=20, verbose_name='उमेर समूह'),
        ),
        migrations.AlterField(
            model_name='wardwisemajoroccupation',
            name='occupation',
            field=models.CharField(choices=[('ANIMAL_HUSBANDRY', 'पशुपालन'), ('BUSINESS', 'व्यापर'), ('DAILY_WAGE', 'दैनिक मजदुरी'), ('FOREIGN_EMPLOYMENT', 'वैदेशिक रोजगार'), ('GOVERNMENT_SERVICE', 'सरकारी सेवा'), ('HOUSEHOLD_WORK', 'घरेलु काम'), ('INDUSTRY', 'उद्योग'), ('NON_GOVERNMENT_SERVICE', 'गैर सरकारी सेवा'), ('OTHER', 'अन्य'), ('OTHER_SELF_EMPLOYMENT', 'अन्य स्व रोजगार'), ('OTHER_UNEMPLOYMENT', 'अन्य बेरोजगार'), ('STUDENT', 'विद्यार्थी')], max_length=50, verbose_name='पेशा'),
        ),
        migrations.AlterUniqueTogether(
            name='wardagewiseeconomicallyactivepopulation',
            unique_together={('ward_number', 'age_group', 'gender')},
        ),
    ]
