# Generated by Django 5.2.3 on 2025-06-16 16:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalityWideCastePopulation',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caste_type', models.CharField(choices=[('BRAHMIN', 'ब्राह्मण'), ('CHHETRI', 'क्षेत्री'), ('MAGAR', 'मगर'), ('TAMANG', 'तामाङ'), ('NEWAR', 'नेवार'), ('THARU', 'थारु'), ('GURUNG', 'गुरुङ'), ('RAI', 'राई'), ('LIMBU', 'लिम्बु'), ('SHERPA', 'शेर्पा'), ('DALIT', 'दलित'), ('MADHESI', 'मधेसी'), ('MUSLIM', 'मुस्लिम'), ('OTHER', 'अन्य')], max_length=100, verbose_name='जातजाति')),
                ('population', models.PositiveIntegerField(blank=True, null=True, verbose_name='जनसंख्या')),
            ],
            options={
                'verbose_name': 'पालिकास्तरीय जातीय जनसंख्या',
                'verbose_name_plural': 'पालिकास्तरीय जातीय जनसंख्या',
                'unique_together': {('caste_type',)},
            },
        ),
        migrations.CreateModel(
            name='MunicipalityWideMotherTonguePopulation',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language_type', models.CharField(choices=[('NEPALI', 'नेपाली'), ('LIMBU', 'लिम्बु'), ('RAI', 'राई'), ('HINDI', 'हिन्दी'), ('NEWARI', 'नेवारी'), ('SHERPA', 'शेर्पा'), ('TAMANG', 'तामाङ'), ('MAITHILI', 'मैथिली'), ('BHOJPURI', 'भोजपुरी'), ('THARU', 'थारु'), ('BAJJIKA', 'बज्जिका'), ('MAGAR', 'मगर'), ('DOTELI', 'डोटेली'), ('URDU', 'उर्दू'), ('AWADI', 'अवधी'), ('GURUNG', 'गुरुङ'), ('ENGLISH', 'अंग्रेजी'), ('OTHER', 'अन्य')], max_length=50, verbose_name='मातृभाषा')),
                ('population', models.PositiveIntegerField(default=0, verbose_name='जनसंख्या')),
            ],
            options={
                'verbose_name': 'पालिकास्तरीय मातृभाषा जनसंख्या',
                'verbose_name_plural': 'पालिकास्तरीय मातृभाषा जनसंख्या',
                'unique_together': {('language_type',)},
            },
        ),
        migrations.CreateModel(
            name='MunicipalityWideReligionPopulation',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('religion_type', models.CharField(choices=[('HINDU', 'हिन्दू'), ('BUDDHIST', 'बौद्ध'), ('KIRANT', 'किरात'), ('CHRISTIAN', 'क्रिश्चियन'), ('ISLAM', 'इस्लाम'), ('NATURE', 'प्रकृति'), ('BON', 'बोन'), ('JAIN', 'जैन'), ('BAHAI', 'बहाई'), ('SIKH', 'सिख'), ('OTHER', 'अन्य')], max_length=20, verbose_name='धर्म')),
                ('population', models.PositiveIntegerField(default=0, verbose_name='जनसंख्या')),
            ],
            options={
                'verbose_name': 'पालिकास्तरीय धार्मिक जनसंख्या',
                'verbose_name_plural': 'पालिकास्तरीय धार्मिक जनसंख्या',
                'unique_together': {('religion_type',)},
            },
        ),
        migrations.DeleteModel(
            name='WardWiseCastePopulation',
        ),
        migrations.DeleteModel(
            name='WardWiseMotherTonguePopulation',
        ),
        migrations.DeleteModel(
            name='WardWiseReligionPopulation',
        ),
    ]
