# Generated by Django 5.2.3 on 2025-06-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demographics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wardwisedeathcause",
            name="death_cause",
            field=models.CharField(
                choices=[
                    ("CANCER", "क्यान्सर"),
                    ("DEATH_BY_OLD_AGE", "कालगतिले"),
                    ("HEART_RELATED_DISEASES", "मुटु सम्बन्धी रोग"),
                    ("BLOOD_PRESSURE_HIGH_AND_LOW_BLOOD_PRESSURE", "रक्तचाप (उच्च/निम्न)"),
                    ("PNEUMONIA", "निमोनिया"),
                    ("ASTHMA", "दमा"),
                    ("DIABETES", "मधुमेह"),
                    ("KIDNEY_RELATED_DISEASES", "मिर्गौला सम्बन्धी रोग"),
                    ("LIVER_RELATED_DISEASES", "कलेजो सम्बन्धी रोग"),
                    ("TYPHOID", "टाइफाइड"),
                    ("FLU", "फ्लु"),
                    ("SUICIDE", "आत्महत्या"),
                    ("TRAFFIC_ACCIDENT", "सवारी दुर्घटना"),
                    ("OTHER_ACCIDENTS", "अन्य दुर्घटना"),
                    ("NATURAL_DISASTER", "प्राकृतिक प्रकोप"),
                    ("NOT_STATED", "कारण नखुलेको"),
                    ("LEPROSY", "कुष्ठरोग"),
                    ("KALA_AZAR", "कालाजार"),
                    ("RESPIRATORY_DISEASES", "श्वासप्रश्वास सम्बन्धी रोग"),
                    ("GASTRIC_ULCER_INTESTINAL_DISEASE", "ग्यास्ट्रिक/आन्द्रा सम्बन्धी रोग"),
                    ("EPILEPSY", "मिर्गी"),
                    ("TUBERCULOSIS", "क्षयरोग"),
                    ("SCABIES", "खटिरा"),
                    ("OTHER", "अन्य"),
                ],
                max_length=50,
                verbose_name="मृत्युको कारण",
            ),
        ),
    ]
