# Generated by Django 5.2.3 on 2025-06-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcategory',
            name='category_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Category Number (e.g., १)'),
        ),
    ]
