# Generated by Django 5.2.3 on 2025-06-15 10:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CulturalSite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="स्थानको नाम")),
                (
                    "name_nepali",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="स्थानको नाम (नेपाली)"
                    ),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "site_type",
                    models.CharField(
                        choices=[
                            ("TEMPLE", "मन्दिर"),
                            ("MONASTERY", "गुम्बा"),
                            ("MOSQUE", "मस्जिद"),
                            ("CHURCH", "गिर्जाघर"),
                            ("HISTORICAL_SITE", "ऐतिहासिक स्थल"),
                            ("CULTURAL_CENTER", "सांस्कृतिक केन्द्र"),
                            ("LIBRARY", "पुस्तकालय"),
                            ("MUSEUM", "संग्रहालय"),
                        ],
                        max_length=20,
                        verbose_name="स्थानको प्रकार",
                    ),
                ),
                (
                    "historical_significance",
                    models.TextField(blank=True, verbose_name="ऐतिहासिक महत्व"),
                ),
                (
                    "cultural_importance",
                    models.TextField(blank=True, verbose_name="सांस्कृतिक महत्व"),
                ),
                (
                    "is_protected",
                    models.BooleanField(default=False, verbose_name="संरक्षित छ"),
                ),
                (
                    "visitor_access",
                    models.BooleanField(default=True, verbose_name="आगन्तुक पहुँच छ"),
                ),
            ],
            options={
                "verbose_name": "सांस्कृतिक स्थल",
                "verbose_name_plural": "सांस्कृतिक स्थलहरू",
            },
        ),
        migrations.CreateModel(
            name="EducationalInstitution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="संस्थाको नाम")),
                (
                    "name_nepali",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="संस्थाको नाम (नेपाली)"
                    ),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("ECD", "बाल विकास केन्द्र"),
                            ("PRIMARY", "आधारभूत विद्यालय"),
                            ("SECONDARY", "माध्यमिक विद्यालय"),
                            ("HIGHER_SECONDARY", "उच्च माध्यमिक विद्यालय"),
                            ("CAMPUS", "क्याम्पस"),
                            ("TECHNICAL", "प्राविधिक शिक्षालय"),
                            ("MADRASA", "मदरसा"),
                            ("MONASTERY", "गुम्बा"),
                            ("CLC", "सामुदायिक शिक्षा केन्द्र"),
                        ],
                        max_length=20,
                        verbose_name="संस्थाको प्रकार",
                    ),
                ),
                (
                    "management_type",
                    models.CharField(
                        choices=[
                            ("COMMUNITY", "सामुदायिक"),
                            ("INSTITUTIONAL", "संस्थागत"),
                            ("RELIGIOUS", "धार्मिक"),
                            ("GOVERNMENT", "सरकारी"),
                        ],
                        max_length=20,
                        verbose_name="व्यवस्थापन प्रकार",
                    ),
                ),
                (
                    "established_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="स्थापना वर्ष"
                    ),
                ),
                (
                    "total_classrooms",
                    models.PositiveIntegerField(
                        default=0, verbose_name="कुल कक्षाकोठा संख्या"
                    ),
                ),
                (
                    "has_computer_lab",
                    models.BooleanField(
                        default=False, verbose_name="कम्प्युटर प्रयोगशाला छ"
                    ),
                ),
                (
                    "has_library",
                    models.BooleanField(default=False, verbose_name="पुस्तकालय छ"),
                ),
                (
                    "has_playground",
                    models.BooleanField(default=False, verbose_name="खेलमैदान छ"),
                ),
                (
                    "has_internet",
                    models.BooleanField(default=False, verbose_name="इन्टरनेट सुविधा छ"),
                ),
                (
                    "is_earthquake_resistant",
                    models.BooleanField(default=False, verbose_name="भूकम्प प्रतिरोधी छ"),
                ),
                ("address", models.TextField(blank=True, verbose_name="ठेगाना")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="फोन नं."),
                ),
            ],
            options={
                "verbose_name": "शैक्षिक संस्था",
                "verbose_name_plural": "शैक्षिक संस्थाहरू",
            },
        ),
        migrations.CreateModel(
            name="HealthFacility",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="स्वास्थ्य संस्थाको नाम"),
                ),
                (
                    "name_nepali",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="स्वास्थ्य संस्थाको नाम (नेपाली)",
                    ),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("HOSPITAL", "अस्पताल"),
                            ("PRIMARY_HEALTH_CENTER", "प्राथमिक स्वास्थ्य केन्द्र"),
                            ("HEALTH_POST", "स्वास्थ्य चौकी"),
                            ("SUB_HEALTH_POST", "उप स्वास्थ्य चौकी"),
                            ("AYURVEDA_CENTER", "आयुर्वेद केन्द्र"),
                            ("PRIVATE_CLINIC", "निजी क्लिनिक"),
                            ("URBAN_HEALTH_CENTER", "शहरी स्वास्थ्य केन्द्र"),
                        ],
                        max_length=30,
                        verbose_name="संस्थाको प्रकार",
                    ),
                ),
                (
                    "bed_capacity",
                    models.PositiveIntegerField(default=0, verbose_name="बेड क्षमता"),
                ),
                (
                    "doctor_count",
                    models.PositiveIntegerField(default=0, verbose_name="डाक्टर संख्या"),
                ),
                (
                    "nurse_count",
                    models.PositiveIntegerField(default=0, verbose_name="नर्स संख्या"),
                ),
                (
                    "health_assistant_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="स्वास्थ्य सहायक संख्या"
                    ),
                ),
                (
                    "has_emergency_service",
                    models.BooleanField(default=False, verbose_name="आकस्मिक सेवा छ"),
                ),
                (
                    "has_maternity_service",
                    models.BooleanField(default=False, verbose_name="सुत्केरी सेवा छ"),
                ),
                (
                    "has_laboratory",
                    models.BooleanField(default=False, verbose_name="प्रयोगशाला छ"),
                ),
                (
                    "has_pharmacy",
                    models.BooleanField(default=False, verbose_name="औषधालय छ"),
                ),
                (
                    "has_ambulance",
                    models.BooleanField(default=False, verbose_name="एम्बुलेन्स सेवा छ"),
                ),
                (
                    "established_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="स्थापना वर्ष"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="ठेगाना")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="फोन नं."),
                ),
            ],
            options={
                "verbose_name": "स्वास्थ्य संस्था",
                "verbose_name_plural": "स्वास्थ्य संस्थाहरू",
            },
        ),
        migrations.CreateModel(
            name="LocalFestival",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="चाडपर्वको नाम")),
                (
                    "name_nepali",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="चाडपर्वको नाम (नेपाली)"
                    ),
                ),
                ("month", models.CharField(max_length=20, verbose_name="महिना")),
                (
                    "duration_days",
                    models.PositiveIntegerField(default=1, verbose_name="अवधि (दिन)"),
                ),
                (
                    "is_religious",
                    models.BooleanField(default=False, verbose_name="धार्मिक छ"),
                ),
                (
                    "is_cultural",
                    models.BooleanField(default=False, verbose_name="सांस्कृतिक छ"),
                ),
                (
                    "celebration_areas",
                    models.TextField(blank=True, verbose_name="मनाउने क्षेत्रहरू"),
                ),
                ("description", models.TextField(blank=True, verbose_name="विवरण")),
            ],
            options={
                "verbose_name": "स्थानीय चाडपर्व",
                "verbose_name_plural": "स्थानीय चाडपर्वहरू",
            },
        ),
        migrations.CreateModel(
            name="SecurityIncident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("THEFT", "चोरी"),
                            ("DOMESTIC_VIOLENCE", "घरेलु हिंसा"),
                            ("ASSAULT", "मारपिट"),
                            ("FRAUD", "ठगी"),
                            ("PROPERTY_DAMAGE", "सम्पत्ति हानि"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=50,
                        verbose_name="घटनाको प्रकार",
                    ),
                ),
                ("incident_date", models.DateField(verbose_name="घटना मिति")),
                ("description", models.TextField(blank=True, verbose_name="विवरण")),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="समाधान भयो"),
                ),
            ],
            options={
                "verbose_name": "सुरक्षा घटना",
                "verbose_name_plural": "सुरक्षा घटनाहरू",
            },
        ),
        migrations.CreateModel(
            name="SportsRecreationFacility",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="सुविधाको नाम")),
                (
                    "name_nepali",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="सुविधाको नाम (नेपाली)"
                    ),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("PLAYGROUND", "खेलमैदान"),
                            ("PARK", "पार्क"),
                            ("PICNIC_SPOT", "पिकनिक स्थल"),
                            ("RECREATION_CENTER", "मनोरञ्जन केन्द्र"),
                            ("SPORTS_COMPLEX", "खेलकुद परिसर"),
                            ("GYMNASIUM", "जिम"),
                        ],
                        max_length=20,
                        verbose_name="सुविधाको प्रकार",
                    ),
                ),
                (
                    "area_size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="क्षेत्रफल (वर्ग मिटर)",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="सार्वजनिक छ"),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "उत्कृष्ट"),
                            ("GOOD", "राम्रो"),
                            ("FAIR", "मध्यम"),
                            ("POOR", "खराब"),
                        ],
                        default="GOOD",
                        max_length=20,
                        verbose_name="अवस्था",
                    ),
                ),
            ],
            options={
                "verbose_name": "खेलकुद तथा मनोरञ्जन सुविधा",
                "verbose_name_plural": "खेलकुद तथा मनोरञ्जन सुविधाहरू",
            },
        ),
        migrations.CreateModel(
            name="YouthClub",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="युवा क्लबको नाम"),
                ),
                (
                    "name_nepali",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="युवा क्लबको नाम (नेपाली)"
                    ),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "total_members",
                    models.PositiveIntegerField(default=0, verbose_name="कुल सदस्य संख्या"),
                ),
                (
                    "male_members",
                    models.PositiveIntegerField(default=0, verbose_name="पुरुष सदस्य"),
                ),
                (
                    "female_members",
                    models.PositiveIntegerField(default=0, verbose_name="महिला सदस्य"),
                ),
                (
                    "is_registered",
                    models.BooleanField(default=False, verbose_name="दर्ता भएको छ"),
                ),
                (
                    "registration_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="दर्ता वर्ष"
                    ),
                ),
            ],
            options={
                "verbose_name": "युवा क्लब",
                "verbose_name_plural": "युवा क्लबहरू",
            },
        ),
        migrations.CreateModel(
            name="WardWiseChildMarriage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "boys_under_18_married",
                    models.PositiveIntegerField(
                        default=0, verbose_name="१८ वर्ष मुनि विवाहित बालक"
                    ),
                ),
                (
                    "girls_under_18_married",
                    models.PositiveIntegerField(
                        default=0, verbose_name="१८ वर्ष मुनि विवाहित बालिका"
                    ),
                ),
            ],
            options={
                "verbose_name": "वडागत बाल विवाह",
                "verbose_name_plural": "वडागत बाल विवाह",
                "unique_together": {("ward_number",)},
            },
        ),
        migrations.CreateModel(
            name="WardWiseEducationLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("ILLITERATE", "निरक्षर"),
                            ("LITERATE", "साक्षर"),
                            ("PRIMARY", "प्राथमिक"),
                            ("LOWER_SECONDARY", "निम्न माध्यमिक"),
                            ("SECONDARY", "माध्यमिक"),
                            ("SLC", "एसएलसी"),
                            ("INTERMEDIATE", "इन्टरमिडिएट"),
                            ("BACHELOR", "स्नातक"),
                            ("MASTER", "स्नातकोत्तर"),
                            ("ABOVE_MASTER", "स्नातकोत्तर माथि"),
                        ],
                        max_length=20,
                        verbose_name="शिक्षा स्तर",
                    ),
                ),
                (
                    "male_population",
                    models.PositiveIntegerField(default=0, verbose_name="पुरुष जनसंख्या"),
                ),
                (
                    "female_population",
                    models.PositiveIntegerField(default=0, verbose_name="महिला जनसंख्या"),
                ),
            ],
            options={
                "verbose_name": "वडागत शिक्षा स्तर",
                "verbose_name_plural": "वडागत शिक्षा स्तर",
                "unique_together": {("ward_number", "education_level")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseHealthIndicators",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "total_births",
                    models.PositiveIntegerField(default=0, verbose_name="कुल जन्म"),
                ),
                (
                    "institutional_births",
                    models.PositiveIntegerField(default=0, verbose_name="संस्थागत जन्म"),
                ),
                (
                    "total_deaths",
                    models.PositiveIntegerField(default=0, verbose_name="कुल मृत्यु"),
                ),
                (
                    "infant_deaths",
                    models.PositiveIntegerField(default=0, verbose_name="बाल मृत्यु"),
                ),
                (
                    "maternal_deaths",
                    models.PositiveIntegerField(default=0, verbose_name="मातृ मृत्यु"),
                ),
                (
                    "fully_immunized_children",
                    models.PositiveIntegerField(
                        default=0, verbose_name="पूर्ण खोप लगाएका बालबालिका"
                    ),
                ),
                (
                    "malnourished_children",
                    models.PositiveIntegerField(
                        default=0, verbose_name="कुपोषित बालबालिका"
                    ),
                ),
            ],
            options={
                "verbose_name": "वडागत स्वास्थ्य सूचकांक",
                "verbose_name_plural": "वडागत स्वास्थ्य सूचकांक",
                "unique_together": {("ward_number",)},
            },
        ),
        migrations.CreateModel(
            name="WardWiseSanitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "toilet_type",
                    models.CharField(
                        choices=[
                            ("FLUSH", "फ्लसको शौचालय"),
                            ("PIT_LATRINE", "खाडलको शौचालय"),
                            ("IMPROVED_PIT", "सुधारिएको खाडलको शौचालय"),
                            ("COMPOSTING", "कम्पोस्टको शौचालय"),
                            ("NO_TOILET", "शौचालय नभएको"),
                        ],
                        max_length=20,
                        verbose_name="शौचालयको प्रकार",
                    ),
                ),
                (
                    "households_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="घरपरिवार संख्या"
                    ),
                ),
            ],
            options={
                "verbose_name": "वडागत सरसफाई",
                "verbose_name_plural": "वडागत सरसफाई",
                "unique_together": {("ward_number", "toilet_type")},
            },
        ),
        migrations.CreateModel(
            name="WardWiseSeniorCitizens",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "senior_citizen_male",
                    models.PositiveIntegerField(
                        default=0, verbose_name="जेष्ठ नागरिक पुरुष"
                    ),
                ),
                (
                    "senior_citizen_female",
                    models.PositiveIntegerField(
                        default=0, verbose_name="जेष्ठ नागरिक महिला"
                    ),
                ),
                (
                    "single_women",
                    models.PositiveIntegerField(default=0, verbose_name="एकल महिला"),
                ),
                (
                    "widows",
                    models.PositiveIntegerField(default=0, verbose_name="विधवा"),
                ),
            ],
            options={
                "verbose_name": "वडागत जेष्ठ नागरिक र एकल महिला",
                "verbose_name_plural": "वडागत जेष्ठ नागरिक र एकल महिला",
                "unique_together": {("ward_number",)},
            },
        ),
        migrations.CreateModel(
            name="WardWiseWaterAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "water_source",
                    models.CharField(
                        choices=[
                            ("TAP_WATER", "धारा/पानी ट्याप"),
                            ("WELL", "इनार"),
                            ("TUBE_WELL", "ट्यूबवेल"),
                            ("SPRING", "मुहान"),
                            ("RIVER", "नदी/खोला"),
                            ("POND", "पोखरी"),
                            ("RAINWATER", "वर्षाको पानी"),
                            ("BOTTLED_WATER", "बोतलको पानी"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=20,
                        verbose_name="पानीको स्रोत",
                    ),
                ),
                (
                    "households_with_access",
                    models.PositiveIntegerField(
                        default=0, verbose_name="पहुँच भएका घरपरिवार"
                    ),
                ),
            ],
            options={
                "verbose_name": "वडागत पानी पहुँच",
                "verbose_name_plural": "वडागत पानी पहुँच",
                "unique_together": {("ward_number", "water_source")},
            },
        ),
        migrations.CreateModel(
            name="StudentEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="सिर्जना मिति"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="अपडेट मिति"),
                ),
                (
                    "grade_level",
                    models.CharField(max_length=20, verbose_name="कक्षा/श्रेणी"),
                ),
                (
                    "academic_year",
                    models.CharField(max_length=10, verbose_name="शैक्षिक सत्र"),
                ),
                (
                    "male_students",
                    models.PositiveIntegerField(default=0, verbose_name="पुरुष विद्यार्थी"),
                ),
                (
                    "female_students",
                    models.PositiveIntegerField(
                        default=0, verbose_name="महिला विद्यार्थी"
                    ),
                ),
                (
                    "dalit_students",
                    models.PositiveIntegerField(
                        default=0, verbose_name="दलित विद्यार्थी"
                    ),
                ),
                (
                    "janajati_students",
                    models.PositiveIntegerField(
                        default=0, verbose_name="जनजाति विद्यार्थी"
                    ),
                ),
                (
                    "disabled_students",
                    models.PositiveIntegerField(
                        default=0, verbose_name="अपाङ्गता भएका विद्यार्थी"
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social.educationalinstitution",
                        verbose_name="शैक्षिक संस्था",
                    ),
                ),
            ],
            options={
                "verbose_name": "विद्यार्थी भर्ना",
                "verbose_name_plural": "विद्यार्थी भर्ना",
                "unique_together": {("institution", "grade_level", "academic_year")},
            },
        ),
    ]
