# Generated by Django 5.2.3 on 2025-06-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wardwiseschooldropout",
            name="cause",
            field=models.CharField(
                choices=[
                    ("LIMITED_SPACE", "सीमित ठाउँ"),
                    ("EXPENSIVE", "महँगो"),
                    ("FAR", "टाढा"),
                    ("HOUSE_HELP", "घरको काम"),
                    ("UNWILLING_PARENTS", "अनिच्छुक अभिभावक"),
                    ("WANTED_STUDY_COMPLETED", "अध्ययन पूरा गर्न चाहना"),
                    ("MARRIAGE", "विवाह"),
                    ("EMPLOYMENT", "रोजगारी"),
                    ("UNKNOWN", "अज्ञात"),
                    ("OTHER", "अन्य"),
                ],
                max_length=25,
                verbose_name="विद्यालय छाड्नुको कारण",
            ),
        ),
    ]
