# Generated by Django 5.2.3 on 2025-06-21 11:34

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_alter_wardwiseschooldropout_cause"),
    ]

    operations = [
        migrations.CreateModel(
            name="WardWiseEducationalInstitution",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "data_year",
                    models.CharField(
                        help_text="Nepali year (e.g., २०७९, २०८०, २०८१)",
                        max_length=10,
                        verbose_name="डेटा वर्ष",
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(
                        help_text="Full name of the educational institution",
                        max_length=255,
                        verbose_name="शैक्षिक संस्थाको नाम",
                    ),
                ),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("COMMUNITY_SCHOOL", "सामुदायिक विद्यालय"),
                            ("RELIGIOUS_SCHOOL", "धार्मिक विद्यालय"),
                            ("TECHNICAL_SCHOOL", "प्राविधिक विद्यालय"),
                            ("COMMUNITY_LEARNING_CENTER", "सामुदायिक सिकाई केन्द्र"),
                            ("PRIVATE_SCHOOL", "निजी विद्यालय"),
                            ("OTHER", "अन्य"),
                        ],
                        default="COMMUNITY_SCHOOL",
                        max_length=50,
                        verbose_name="संस्थाको प्रकार",
                    ),
                ),
                (
                    "school_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRIMARY", "प्राथमिक"),
                            ("LOWER_SECONDARY", "निम्न माध्यमिक"),
                            ("SECONDARY", "माध्यमिक"),
                            ("HIGHER_SECONDARY", "उच्च माध्यमिक"),
                            ("EARLY_CHILDHOOD", "बाल विकास केन्द्र"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="विद्यालयको तह",
                    ),
                ),
                (
                    "male_students",
                    models.PositiveIntegerField(
                        default=0, verbose_name="पुरुष विद्यार्थी संख्या"
                    ),
                ),
                (
                    "female_students",
                    models.PositiveIntegerField(
                        default=0, verbose_name="महिला विद्यार्थी संख्या"
                    ),
                ),
                (
                    "total_teachers",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="कुल शिक्षक संख्या"
                    ),
                ),
                (
                    "is_operational",
                    models.BooleanField(default=True, verbose_name="सञ्चालनमा छ/छैन"),
                ),
            ],
            options={
                "verbose_name": "वडागत शैक्षिक संस्था र विद्यार्थी विवरण",
                "verbose_name_plural": "वडागत शैक्षिक संस्था र विद्यार्थी विवरण",
                "unique_together": {("ward_number", "data_year", "institution_name")},
            },
        ),
    ]
