# Generated by Django 5.2.3 on 2025-06-21 12:03

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_wardwiseeducationalinstitution"),
    ]

    operations = [
        migrations.CreateModel(
            name="WardWiseTeacherStaffing",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(max_length=255, verbose_name="विद्यालयको नाम"),
                ),
                (
                    "institution_level",
                    models.CharField(
                        choices=[
                            ("PRIMARY", "प्राथमिक"),
                            ("LOWER_SECONDARY", "निम्न माध्यमिक"),
                            ("SECONDARY", "माध्यमिक"),
                            ("HIGHER_SECONDARY", "उच्च माध्यमिक"),
                            ("EARLY_CHILDHOOD", "बाल विकास केन्द्र"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=20,
                        verbose_name="संस्थाको तह",
                    ),
                ),
                (
                    "teacher_level",
                    models.CharField(
                        choices=[
                            ("CHILD_DEVELOPMENT", "बाल विकास"),
                            ("BASIC_1_5", "आधारभूत १-५"),
                            ("BASIC_6_8", "आधारभूत ६-८"),
                            ("BASIC_9_10", "आधारभूत ९-१०"),
                            ("BASIC_11_12", "आधारभूत ११-१२"),
                        ],
                        max_length=30,
                        verbose_name="शिक्षकको तह",
                    ),
                ),
                (
                    "position_type",
                    models.CharField(
                        choices=[
                            ("APPROVED_QUOTA", "स्वीकृत दरबन्दी"),
                            ("RELIEF", "राहत"),
                            ("FEDERAL_GRANT", "संघीय अनुदान"),
                            ("RM_GRANT", "गाउँपालिका अनुदान"),
                            ("PRIVATE_SOURCE", "निजी स्रोत"),
                        ],
                        max_length=30,
                        verbose_name="पदको प्रकार",
                    ),
                ),
                (
                    "teacher_count",
                    models.PositiveIntegerField(default=0, verbose_name="शिक्षक संख्या"),
                ),
            ],
            options={
                "verbose_name": "वडागत शिक्षक र शैक्षिक जनशक्ति",
                "verbose_name_plural": "वडागत शिक्षक र शैक्षिक जनशक्ति",
                "db_table": "social_ward_wise_teacher_staffing",
                "unique_together": {
                    ("ward_number", "school_name", "teacher_level", "position_type")
                },
            },
        ),
        migrations.CreateModel(
            name="WardWiseTeacherSummary",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher_level",
                    models.CharField(
                        choices=[
                            ("CHILD_DEVELOPMENT", "बाल विकास"),
                            ("BASIC_1_5", "आधारभूत १-५"),
                            ("BASIC_6_8", "आधारभूत ६-८"),
                            ("BASIC_9_10", "आधारभूत ९-१०"),
                            ("BASIC_11_12", "आधारभूत ११-१२"),
                        ],
                        max_length=30,
                        verbose_name="शिक्षकको तह",
                    ),
                ),
                (
                    "position_type",
                    models.CharField(
                        choices=[
                            ("APPROVED_QUOTA", "स्वीकृत दरबन्दी"),
                            ("RELIEF", "राहत"),
                            ("FEDERAL_GRANT", "संघीय अनुदान"),
                            ("RM_GRANT", "गाउँपालिका अनुदान"),
                            ("PRIVATE_SOURCE", "निजी स्रोत"),
                        ],
                        max_length=30,
                        verbose_name="पदको प्रकार",
                    ),
                ),
                (
                    "total_teachers",
                    models.PositiveIntegerField(default=0, verbose_name="कुल शिक्षक"),
                ),
            ],
            options={
                "verbose_name": "शिक्षक र शैक्षिक जनशक्ति सारांश",
                "verbose_name_plural": "शिक्षक र शैक्षिक जनशक्ति सारांश",
                "db_table": "social_ward_wise_teacher_summary",
                "unique_together": {("teacher_level", "position_type")},
            },
        ),
    ]
