# Generated by Django 5.2.3 on 2025-06-21 15:00

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0004_add_teacher_staffing_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="WardWiseHealthInstitution",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="वडा नं.",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the health institution",
                        max_length=255,
                        verbose_name="स्वास्थ्य संस्थाको नाम",
                    ),
                ),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("HOSPITAL", "अस्पताल"),
                            ("PRIMARY_HEALTH_CENTER", "प्राथमिक स्वास्थ्य केन्द्र"),
                            ("HEALTH_POST", "स्वास्थ्य चौकी"),
                            ("AYURVEDA_CENTER", "आयुर्वेद केन्द्र"),
                            ("COMMUNITY_HEALTH_UNIT", "सामुदायिक स्वास्थ्य इकाइ"),
                            ("SUB_HEALTH_POST", "उप स्वास्थ्य चौकी"),
                            ("BIRTHING_CENTER", "प्रसूति केन्द्र"),
                            ("CLINIC", "क्लिनिक"),
                            ("OTHER", "अन्य"),
                        ],
                        max_length=50,
                        verbose_name="संस्थाको प्रकार",
                    ),
                ),
            ],
            options={
                "verbose_name": "वडागत स्वास्थ्य संस्था विवरण",
                "verbose_name_plural": "वडागत स्वास्थ्य संस्था विवरण",
                "unique_together": {("ward_number", "name")},
            },
        ),
        migrations.DeleteModel(
            name="HealthInstitution",
        ),
    ]
